name: Test Deploy to GitHub Pages

on:
  workflow_dispatch:
    branches:
      - main
    # Review gh actions docs if you want to further define triggers, paths, etc
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#on

jobs:
  deploy:
    name: Test Deploy to GitHub Pages
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: website
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm

      - name: Install dependencies
        run: npm ci
      - name: Update Config BaseUrl
        run: | 
          sed -i "s+baseUrl: '/'+baseUrl: '/PlayStation-Stars/'+g" docusaurus.config.js
      - name: Build website
        run: npm run build